import express from "express";
import request from "supertest";
import { describe, expect, it } from "vitest";
import { ListDocumentsQueryParams } from "@workspace/api-zod";

// Mini-app that re-implements the route's parse boundary so the test pins
// down the real wire behavior: Express+qs gives a bare string for a single
// `tagIds=...` and an array for repeated `tagIds`. The route normalises a
// bare string to a one-element array before calling Zod.
function makeBoundaryApp() {
  const app = express();
  app.get("/list", (req, res) => {
    const q = { ...(req.query as Record<string, unknown>) };
    if (typeof q.tagIds === "string") q.tagIds = [q.tagIds];
    try {
      const parsed = ListDocumentsQueryParams.parse(q);
      res.json({
        ok: true,
        tagIds: parsed.tagIds ?? null,
        dateFrom: parsed.dateFrom?.toISOString() ?? null,
        dateTo: parsed.dateTo?.toISOString() ?? null,
        academicYear: parsed.academicYear ?? null,
      });
    } catch (err) {
      res.status(400).json({ ok: false, err: (err as Error).message });
    }
  });
  return app;
}

/**
 * These tests guard the boundary parsing of the list-documents query string
 * — i.e. they verify the Zod schema generated by orval correctly coerces
 * what arrives off the wire (Express `req.query` shapes) into the types the
 * service layer expects (Date, number, string[]).
 *
 * The bug we are guarding against: dateFrom/dateTo previously stayed as
 * strings because `format: date` query params were not in orval's coerce
 * config, which crashed inside the repository when Drizzle tried to bind a
 * string into a `timestamp` parameter. Repeated tagIds had to be observed as
 * an array even when only one selection was made.
 */
describe("ListDocumentsQueryParams coercion", () => {
  it("coerces dateFrom and dateTo from ISO strings to Date instances", () => {
    const parsed = ListDocumentsQueryParams.parse({
      dateFrom: "2025-01-01",
      dateTo: "2025-12-31",
    });
    expect(parsed.dateFrom).toBeInstanceOf(Date);
    expect(parsed.dateTo).toBeInstanceOf(Date);
    expect(parsed.dateFrom?.toISOString().slice(0, 10)).toBe("2025-01-01");
    expect(parsed.dateTo?.toISOString().slice(0, 10)).toBe("2025-12-31");
  });

  it("coerces academicYear from a query string to a number", () => {
    const parsed = ListDocumentsQueryParams.parse({ academicYear: "2024" });
    expect(parsed.academicYear).toBe(2024);
  });

  it("rejects an obviously invalid date string", () => {
    expect(() =>
      ListDocumentsQueryParams.parse({ dateFrom: "not-a-date" }),
    ).toThrow();
  });
});

describe("/documents tagIds boundary (mimics route normalization)", () => {
  const t1 = "00000000-0000-0000-0000-000000000001";
  const t2 = "00000000-0000-0000-0000-000000000002";

  it("accepts a single ?tagIds=... value (bare string from qs)", async () => {
    const res = await request(makeBoundaryApp()).get(`/list?tagIds=${t1}`);
    expect(res.status).toBe(200);
    expect(res.body.tagIds).toEqual([t1]);
  });

  it("accepts repeated ?tagIds=...&tagIds=... values (array from qs)", async () => {
    const res = await request(makeBoundaryApp()).get(
      `/list?tagIds=${t1}&tagIds=${t2}`,
    );
    expect(res.status).toBe(200);
    expect(res.body.tagIds).toEqual([t1, t2]);
  });

  it("parses ?dateFrom=...&dateTo=... ISO strings off the wire", async () => {
    const res = await request(makeBoundaryApp()).get(
      "/list?dateFrom=2025-01-01&dateTo=2025-12-31",
    );
    expect(res.status).toBe(200);
    expect(res.body.dateFrom?.slice(0, 10)).toBe("2025-01-01");
    expect(res.body.dateTo?.slice(0, 10)).toBe("2025-12-31");
  });

  it("400s when a date param is unparseable", async () => {
    const res = await request(makeBoundaryApp()).get(
      "/list?dateFrom=not-a-date",
    );
    expect(res.status).toBe(400);
  });
});
